### ISSUE TITLE
gyp: drafter/drafter.gyp not found

### ISSUE THREAD

**Issue by artlogic** [apiaryio/protagonist#100]
When trying to install the latest release (1.1.0) with npm, I receive this error:

```
$ npm install protagonist
\
> protagonist@1.1.0 install /Users/artlogic/Code/appserver/node_modules/protagonist
> node-gyp rebuild

gyp: drafter/drafter.gyp not found (cwd: /Users/artlogic/Code/appserver/node_modules/protagonist) while loading dependencies of binding.gyp while trying to load binding.gyp
```

**Comment by catesandrew** [comment]
+1 same thing

**Comment by accidentaldevelopment** [comment]
+1 same here

**Comment by Silvercast** [comment]
+1

**Comment by kylef** [comment]
Sorry about this. We're looking into this and will create an update to solve the problem soon.

**Comment by hwestbrook** [comment]
+1

**Comment by rvlander** [comment]
+1

**Comment by danielgtaylor** [comment]
@artlogic @catesandrew @accidentaldevelopment @Silvercast @hwestbrook @rvlander this should now be fixed in the 1.1.1 patch release. Please try it out and let us know if there are any other issues!

**Comment by artlogic** [comment]
@danielgtaylor - works with node 4.2.1 - thanks!

**Comment by catesandrew** [comment]
working with v4.2.1 here too, thanks!
