### ISSUE TITLE
Installing issues @Ubuntu + Node v4.2.x

### ISSUE THREAD

**Issue by romansklenar** [apiaryio/protagonist#115]
protagonist@1.2.3 installation fails on Ubuntu using Node v4.2.x when installing protagonist as dredd@1.0.2 dependency

```bash
gcc --version # gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
c++ --version # c++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
node -v # v4.2.4
node-gyp -v # v3.0.3
npm -v # v2.14.12
```

More info: https://gist.github.com/romansklenar/a2f3813b87bca2cd95b9

**Comment by w-vi** [comment]
@romansklenar  thanks for the report, just curious how much memory has the vagrant box, as gcc internal errors are very rare and very often it is a not enough memory problem.

**Comment by kylef** [comment]
Unrelated to GCC crashing, however NPM is also failing in the second log due to permissions problem. NPM is ran as a user that doesn't have permission to install globally (due to the `-g` option it's installing in `/usr/lib/node_modules`).

```
64 error Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/dredd'
64 error     at Error (native)
64 error  { [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/dredd']
...
65 error Please try running this command again as root/Administrator.
```

**Comment by romansklenar** [comment]
NPM `-g` installation was easily fixed with using sudo but installation still failed.
@w-vi was right, it was a memory related problem. Vagrant box had just 512MB of RAM, after I increased it to 768MB, I was able to install dredd and it's dependencies including protagonist.

Thank you for your help, you can consider this issue closed.

**Comment by kylef** [comment]
Thanks @romansklenar, glad we figured it out.

**Comment by hannesvdvreken** [comment]
Having the same issues, except on a 1GB server. How feasible is it to

- downscale memory footprint of the build fase
- package with pre-built node bindings
- make a pure JS implementation (can you point me to documentation that explains why this needs compiling?)

Having to upscale a 1GB server for hosting static files seems... unproductive.
