### ISSUE TITLE
1.2.4 is broken

### ISSUE THREAD

**Issue by aichholzer** [apiaryio/protagonist#119]
With the latest version `1.2.4`, `npm install protagonist` fails with error `gyp: drafter/drafter.gyp not found` - Tested with many of the supported Nodejs versions.

`npm install protagonist@1.2.3` works as expected.

**Comment by kylef** [comment]
Resolved by [protagonist 1.2.5](https://github.com/apiaryio/protagonist/releases/tag/v1.2.5).

**Comment by aichholzer** [comment]
:+1:
