### ISSUE TITLE
Fix installation on windows

### ISSUE THREAD

**Issue by kylef** [apiaryio/protagonist#121]
Since some of the API Blueprint editor plugins (such as for Atom) depend on Protagonist, more and more people are trying to use Protagonist on Windows and having difficulties getting it installed. I think Aglio and Dredd also get various support requests related to Protagonist on Windows.

I'm not sure how to address this exactly, but here are some thoughts:

- Clear documentation on Windows dependencies
- Better error messages, sometimes the error messages don't indicate what the problem is (i.e, missing python, missing compiler, etc).

    example:

    ```
    > protagonist@1.2.5 install C:\Users\AARMST~1\AppData\Local\Temp\apm-install-dir-116019-7824-177is5c\node_modules\linter-api-blueprint\node_modules\protagonist 
    > node-gyp rebuild

    C:\Users\AARMST~1\AppData\Local\Temp\apm-install-dir-116019-7824-177is5c\node_modules\linter-api-blueprint\node_modules\protagonist>if not defined npm_config_node_gyp (node     "C:\Users\aarmstrong\AppData\Local\atom\app-1.4.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node rebuild )

    npm WARN engine refract-query@0.0.1: wanted: {"node":"5.1.x","npm":"3.3.x"} (current: {"node":"0.10.40","npm":"2.13.3"})
    gypnpm ERR! Windows_NT 6.2.9200 
    npm ERR! argv "C:\\Users\\aarmstrong\\AppData\\Local\\atom\\app-1.4.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\aarmstrong\\AppData\\Local\\atom\\app-1.4.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\aarmstrong\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\aarmstrong\\.atom\\.apmrc" "install" "C:\\Users\\AARMST~1\\AppData\\Local\\Temp\\d-116019-7824-1updbci\\package.tgz" "--target=0.34.5" "--arch=ia32" 
    npm ERR! node v0.10.40 
    npm ERR! npm v2.13.3 
    npm ERR! code ELIFECYCLE

    npm ERR! protagonist@1.2.5 install: `node-gyp rebuild` 
    npm ERR! Exit status 1 
    npm ERR! 
    npm ERR! Failed at the protagonist@1.2.5 install script 'node-gyp rebuild'. 
    npm ERR! This is most likely a problem with the protagonist package, 
    npm ERR! not with npm itself. 
    npm ERR! Tell the author that this fails on your system: 
    npm ERR! node-gyp rebuild 
    npm ERR! You can get their info via: 
    npm ERR! npm owner ls protagonist 
    npm ERR! There is likely additional logging output above.
    ```

**Comment by w-vi** [comment]
Just curious as I have no knowledge on the topic, but can we actually distribute an installer? So no more need for compiler etc? I don't know if that works with node.js extensions but it would solve a lot of the hassle

**Comment by kylef** [comment]
@w-vi I have a feeling that won't be possible. For example, Atom bundles node itself. The installation instructions for [Atom linter plugin](https://github.com/zdne/linter-api-blueprint) are simply:

```shell
$ apm install linter-api-blueprint
```

From what I can make out, Atom/Node will build it's dependencies.

**Comment by w-vi** [comment]
I see, building stuff from source is a *NIX thing it never worked well on Windows so it probably never will be easy.

**Comment by w-vi** [comment]
Or, can we make the `npm` package to include a prebuilt binary or have some extra package inlcuding the binary or something along these lines?

**Comment by zdne** [comment]
I am running into the same issues. Trying to get more data.

**Comment by zdne** [comment]
No additional info from atom logs. Failed to locate where `$apm install` puts logs from the actual `npm` call. 

Here is the output from `apm install --verbose linter-api-blueprint`:


```
> protagonist@1.2.5 install C:\Users\Zdenek\AppData\Local\Temp\apm-install-dir-116027-4508-1fgjwsj\node_modules\linter-api-blueprint\node_modules\protagonist
> node-gyp rebuild


C:\Users\Zdenek\AppData\Local\Temp\apm-install-dir-116027-4508-1fgjwsj\node_modules\linter-api-blueprint\node_modules\protagonist>if not defined npm_config_node_gyp (node "C:\Users\Zdenek\AppData\Local\atom\app-1.4.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "14.0", "4.0".
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Zdenek\\AppData\\Local\\atom\\app-1.4.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Zdenek\\AppData\\Local\\atom\\app-1.4.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Zdenek\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Zdenek\\.atom\\.apmrc" "install" "C:\\Users\\Zdenek\\AppData\\Local\\Temp\\d-116027-4508-1k8t6e1\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! protagonist@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protagonist@1.2.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.
```

**Comment by zdne** [comment]
Also I would argue that the title should be "fix" (not "improve") the installation

**Comment by zdne** [comment]
This issue seems to be caused by the bundled `node-gyp` with the combination of MSVS2015. If that is the case running `set GYP_MSVS_VERSION=2015` before `npm install protagonist` (or any other native tool really will do the trick. 

See 

https://github.com/nodejs/node-gyp/issues/629 

and

https://www.serverpals.com/blog/building-using-node-gyp-with-visual-studio-express-2015-on-windows-10-pro-x64

**Comment by FrankyBoy** [comment]
So much +1, it's ridiculous that I need to install both python as well as visual studio (with the proper options set!) to get a nodejs package to install!

**Comment by zdne** [comment]
@FrankyBoy depends on what you are after you might use `drafter.js` as a drop in replacement for protagonist (same intefrace, JS only, much much slower but hopefully faster to install). 

https://www.npmjs.com/package/drafter.js

**Comment by anyong** [comment]
Impossible to install on Windows. I've got all the C++ redistributables installed for 2008, 2010, 2012, 2013, 2015, got msvs_version=2015 set in npm and in GYP_MSVS_VERSION=2015 variable. All other C++ stuff so far has compiled without any issues (like node-sass).

**Comment by pksunkara** [comment]
@anyong You can try using the https://www.npmjs.com/package/drafter.js even though it is a bit slower.

**Comment by MattiJarvinen-BA** [comment]
Weird couldn't get it to install through atom UI but `apm install --verbose linter-api-blueprint` worked on cmdline.

**Comment by kylef** [comment]
I think [Drafter NPM](https://github.com/apiaryio/drafter-npm) sufficiently solves this problem. If NPM cannot build Protagonist, it will then automatically fallback to drafter.js, the pure JS version of Drafter.

Tools such as Aglio can use drafter-npm to provide installation without a compiler and other non NPM dependencies (https://github.com/danielgtaylor/aglio/pull/277).
