### ISSUE TITLE
Node-gyp Couldn't compile 

### ISSUE THREAD

**Issue by JefStat** [apiaryio/protagonist#122]
[npm-debug.txt](https://github.com/apiaryio/protagonist/files/99773/npm-debug.txt)

> protagonist@1.2.5 install /Volumes/TERRA/projects/connect-checkin/node_modules/dredd/node_modules/protagonist
> node-gyp rebuild

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp: /Users/user/.node-gyp/5.4.1/common.gypi not found (cwd: /Volumes/TERRA/projects/project/node_modules/dredd/node_modules/protagonist) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/user/.node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by kylef** [comment]
@JefStat Can I confirm if you have Xcode and/or Xcode Command Line tools?

You should be able to confirm with:

```shell
$ xcode-select --install
```

**Comment by JefStat** [comment]
@kylef that's the fix must of missed reinstalling the command line tools after an osx or xcode upgrade.

**Comment by kylef** [comment]
Great :ok_hand: !
