### ISSUE TITLE
Install fails on Centos 6.7, 64-bit

### ISSUE THREAD

**Issue by dhoffman34** [apiaryio/protagonist#128]
I am trying to run `npm install -g dredd` on our CI server. It fails with this output:  https://gist.github.com/dhoffman34/34397b9b8a4f22a1f28a

Any ideas on how to fix this issue?

**Comment by w-vi** [comment]
CentOS has by default pretty old gcc, please  see https://github.com/apiaryio/protagonist/issues/126 for more details.

**Comment by dhoffman34** [comment]
Ah, I got it working now.  Thanks!
