### ISSUE TITLE
Include statement doesn't produce correct assets if attributes are defined in resource and referenced from payload or action

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/protagonist#133]
[This Dredd build](https://travis-ci.org/apiaryio/dredd/jobs/111707928) shows that some assets are not rendered correctly when using Include statement while attributes are defined in resource and referenced from payload or action. See my report in https://github.com/apiaryio/dredd/issues/354#issuecomment-188705444.

Until I'm able to get tests in https://github.com/apiaryio/dredd/pull/380 passing, I won't consider this issue as resolved.

**Comment by honzajavorek** [comment]
I updated my PR to depend on `v1.3.0-pre.0`, but results of tests didn't change at all. Please see https://github.com/apiaryio/dredd/pull/380 - I've updated the PR description to contain an overview table of what's broken and what works correctly. Reopening https://github.com/apiaryio/drafter/issues/248.

**Comment by pksunkara** [comment]
This has been fixed in `v1.3.0-pre.1`
