### ISSUE TITLE
Segfault-handler throwing exception saying segfault-handler-native.node not found 

### ISSUE THREAD

**Issue by meoster** [apiaryio/protagonist#14]
For segfault-handler module. Name inside binding.gyp and index.js must be the same. It is currently using segfault-handler-native.

Got protagonist working with my latest ubuntu after renaming to be the same.

This is not a protagonist issue but a note for others getting it to work.

**Comment by pksunkara** [comment]
This should be solved since segfault-handler is fixed and we are always using it's master branch. Close?

**Comment by pksunkara** [comment]
@meoster This has been fixed in segfault-handler master branch. Please reopen if still getting the error.
