### ISSUE TITLE
Don't require python

### ISSUE THREAD

**Issue by FrankyBoy** [apiaryio/protagonist#140]
Basically because it makes installing and setting up stuff a pain in the ass.

**Comment by pksunkara** [comment]
Unfortunately node-gyp requires it. :disappointed:

**Comment by FrankyBoy** [comment]
Don't require node-gyp

**Comment by pksunkara** [comment]
Would love to get some alternatives.

**Comment by FrankyBoy** [comment]
well, there is now an (experimental) emscripten-port of drafter I saw somewhere, so in case of no python you could fall back to that. That would also fix the issue that everyone needs a c-compiler to install a js library ...

**Comment by pksunkara** [comment]
@FrankyBoy We are the one who are generating the emscripten port of drafter at https://npmjs.com/package/drafter.js. But it is a lot slower than C++ one.

We can probably look into CMake based build system for native node module.

**Comment by FrankyBoy** [comment]
I have to say, I am not too concerned about speed (that's just Jenkins' time in a separate build that is spent), for me it's all about ease of use.

**Comment by pksunkara** [comment]
@FrankyBoy Then you can use `drafter.js` directly in place of `protagonist`.

**Comment by w-vi** [comment]
@FrankyBoy The idea behind the drafter.js version is that whoever needs protagonist can make it an optional dependency and use drafter.js as a fallback, but because it is much slower we are leaving this decision on the protagonist consumer. Sometimes performance matters sometimes not.

**Comment by FrankyBoy** [comment]
@w-vi so I'd need to poke the aglio-guys on this I guess ... cya over there.
