### ISSUE TITLE
npm install fails on 64bit openSuse

### ISSUE THREAD

**Issue by jano-petras** [apiaryio/protagonist#15]
Unable to install protagonist on 64bit openSuse linux install. 

<pre>
xxxx@linux:~> npm install protagonist
npm http GET https://registry.npmjs.org/protagonist
npm http 304 https://registry.npmjs.org/protagonist
npm http GET https://registry.npmjs.org/protagonist/-/protagonist-0.10.0.tgz
npm http 200 https://registry.npmjs.org/protagonist/-/protagonist-0.10.0.tgz

> protagonist@0.10.0 install /home/xxxx/node_modules/protagonist
> node-gyp rebuild

gyp: /usr/share/node/common.gypi not found (cwd: /home/xxxx/node_modules/protagonist) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/configure.js:417:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:784:12)
gyp ERR! System Linux 3.11.10-7-desktop
gyp ERR! command "node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/xxxx/node_modules/protagonist
gyp ERR! node -v v0.10.5
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! protagonist@0.10.0 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the protagonist@0.10.0 install script.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.10-7-desktop
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "protagonist"
npm ERR! cwd /home/xxxx
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/xxxx/npm-debug.log
npm ERR! not ok code 0
xxxx@linux:~> 
</pre>

**Comment by akademy** [comment]
I had this problem on OpenSuse and @cesarizu suggestion worked. Just install devel with:
zypper in nodejs-devel

(Note: it's called "nodejs-devel" not "node-devel" as @mustela mentioned.)

**Comment by pksunkara** [comment]
@devsdmf Updating your npm should solve your issue.

```
npm install -g npm@latest
```

@mustela's issue has been solved in danielgtaylor/aglio#54
