### ISSUE TITLE
Installation fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by betterphp** [apiaryio/protagonist#155]
Sorry this feels like the sort of thing that's probably going to turn out to be user error - I'm getting this when trying to build from the current master branch. Ended up with the same error when trying to install aglio from npm.

~~~
jacek@jacek-work-laptop: protagonist $ npm install

> protagonist@1.3.3 install /home/jacek/protagonist
> node-gyp rebuild

gyp: drafter/drafter.gyp not found (cwd: /home/jacek/protagonist) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jacek/protagonist
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! protagonist@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@1.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protagonist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jacek/protagonist/npm-debug.log
~~~

There seem to have been similar issues in the past but the solutions there don't seem to work for me,

**Comment by mhueter** [comment]
same issue on Ubuntu 16.04 (docker image). It happens when I run `npm install` which has dredd in it: `"dredd": "1.1.0"`

I get no errors when I run `npm install dredd@1.1.0 -g`. I only get the protagonist / node-gyp dependency error above when I do a normal npm install. 

On the docker image I have Ubuntu 16.04 I have python 2.7, gcc, make, node v6.2.2, npm  v3.9.5

**Comment by kylef** [comment]
Hi @betterphp 

It seems you didn't clone the git submodules for this repository hence some files in submodules are not found (gyp: drafter/drafter.gyp not found (cwd: /home/jacek/protagonist) while loading dependencies of binding.gyp while trying to load binding.gyp).

Please check the steps at https://github.com/apiaryio/protagonist#hacking-protagonist

**Comment by kylef** [comment]
@mhueter It seems your problem is a separate issue (installing Protagonist via Dredd, and not installing Protagonist directly from the Protagonist repository). Could you please file a separate issue including your error log.

**Comment by mhueter** [comment]
@kylef alright https://github.com/apiaryio/protagonist/issues/156
