### ISSUE TITLE
Node v0.11 support

### ISSUE THREAD

**Issue by zdne** [apiaryio/protagonist#16]
Also see <http://stackoverflow.com/questions/22763774/jenkins-dredd-npm-err-failed-at-the-protagonist0-8-0-install-script?noredirect=1#comment35235905_22763774>

**Comment by zdne** [comment]
I have started to play with the new v8 API seems there were quite big changes the WIP branch is here: https://github.com/apiaryio/protagonist/tree/zdne/node-v0.11-support 

New Node documentation available here: https://github.com/joyent/node/blob/v0.11.14-release/doc/api/addons.markdown

**Comment by danielgtaylor** [comment]
+1 (this should also add support for [iojs](https://iojs.org/) 1.x)

**Comment by yakovkhalinsky** [comment]
Will just add this now happens on the new Node.js 0.12 release

**Comment by jacksonj04** [comment]
+1

**Comment by Almad** [comment]
@zdne Hmm, will this make the "new" protagonist versions backward-incompatible with 0.10?

**Comment by pksunkara** [comment]
@Almad I am looking at https://github.com/rvagg/nan using which we can still be backward compatible

**Comment by pksunkara** [comment]
iojs/io.js#456

**Comment by pksunkara** [comment]
protagonist-experimental@0.18.7 now supports node.js ~0.8.15, 0.10.x, 0.11.x, 0.12.x and io.js v1.x.x

**Comment by demohi** [comment]
:+1:

**Comment by zdne** [comment]
@pksunkara you can't close this issue until it was released as protagonist :-1:

**Comment by michaelgilley** [comment]
Is there an ETA for fix on this issue? It's the one thing stopping us from moving to 0.12 or io.js and I'm about to drop it if need be.

**Comment by pksunkara** [comment]
@michaelgilley It has been fixed and beta released at `protagonist-experimental@0.18.7`. We are looking to do an official release as soon as possible.

**Comment by michaelgilley** [comment]
Great! Thank you!

**Comment by bappelt** [comment]
+1

**Comment by sadjow** [comment]
+1

**Comment by jwhitehorn** [comment]
Any ETA for an official release?

**Comment by zdne** [comment]
@jwhitehorn less than two weeks

**Comment by zdne** [comment]
Until then please use `protagonist-experimental` if possible

**Comment by mansona** [comment]
Can you release it as a pre-release tag until then? https://github.com/npm/node-semver#prerelease-tags that way I can manually update sub-dependancies and have it still satisfy the version

**Comment by lholmquist** [comment]
+1 to a pre-release

**Comment by RHavar** [comment]
Yeah, pre-release would be much nicer

**Comment by zdne** [comment]
We are looking into this. Either we will have stable release this week or we will switch to the pre-release. Thanks for your patience.

**Comment by pksunkara** [comment]
We have released a pre-release of protagonist version `0.19.0-rc` today. You can install it using the following command

```
npm install protagonist@0.19.0-rc
```

**Comment by zdne** [comment]
the latest protagonist `v0.19.x` supports node.js v0.10, v0.11, v0.12 as well as io.js
