### ISSUE TITLE
Troubles with installing globally on Linux via npm.

### ISSUE THREAD

**Issue by iterq1** [apiaryio/protagonist#163]
Hi! Have the same issue as https://github.com/apiaryio/protagonist/issues/127.

I have installed `build-essential`, but installation of api-mock (or protagonist separately) fails with error log listed below.

```
make: *** [Release/obj.target/protagonist/src/annotation.o] Ошибка 1
make: Выход из каталога `/usr/local/lib/node_modules/protagonist/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/protagonist
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "protagonist@1.2.6"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! protagonist@1.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@1.2.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protagonist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

```

**Comment by pksunkara** [comment]
What is the distro you are using? /cc @w-vi

**Comment by w-vi** [comment]
It's some debian based, are you sure you have gcc 4.8+ installed?

**Comment by iterq1** [comment]
@pksunkara I'm using Linux Mint 17.3.

By the way I solved this issue by switching to node v4 from v6.
But protagonist README.md says
> Tested with node.js ~0.8.15, 0.10.x, 0.12.x, 4, 6

so issue isn't solved I think.

@w-vi 
`gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) `

**Comment by pksunkara** [comment]
As you can see here our protagonist does work on https://travis-ci.org/apiaryio/protagonist/jobs/158188296. Maybe can you try reinstalling node v6 and try again?

**Comment by w-vi** [comment]
Strange we are testing against all of those node versions on ubuntu and everything seems to be working well. I am mostly working with node 6 and protagonist installs correctly. So there is some deeper issue.

**Comment by iterq1** [comment]
@w-vi @pksunkara I've installed it again within nvm environment with node v6.6.0. It worked, both, global and local installation. So probably there were some troubles with my system environment. Thank you.

**Comment by pksunkara** [comment]
Yeah, I thought so since you installed `build-essential` after installing node.
