### ISSUE TITLE
Installing issues @W7 + WebStorm + NPM

### ISSUE THREAD

**Issue by raisty** [apiaryio/protagonist#18]
At first I install node-gyp 0.13.0, then I want install protagonist (latest - 0.11.0). But there is always error:

Install packages failed: Error occurred when installing package protagonist. 
"C:\Program Files\nodejs\npm.cmd" install protagonist

Exit code: 1

Standard error:
npm http GET https://registry.npmjs.org/protagonist
npm http 304 https://registry.npmjs.org/protagonist
gypnpm ERR! protagonist@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@0.11.0 install script.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "protagonist"
npm ERR! cwd C:\Users\Work\WebstormProjects\trader
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.26
npm ERR! code ELIFECYCLE
npm

Standard output:

> protagonist@0.11.0 install C:\Users\Work\WebstormProjects\trader\node_modules\protagonist
> node-gyp rebuild

C:\Users\Work\WebstormProjects\trader\node_modules\protagonist>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

**Comment by pksunkara** [comment]
@max258 Can you try using a later npm version? preferably 2.x.x

**Comment by kylef** [comment]
Since this issue was originally created, we've now introduced a new package ([Drafter NPM](https://github.com/apiaryio/drafter-npm)) which can be used to install Protagonist, or fallback on a pure javascript version of the API Blueprint parser.

If you're having difficulties setting up your environment I'd recommend using https://github.com/apiaryio/drafter-npm instead.
