### ISSUE TITLE
node-gyp rebuild failure on Mac OS 10.12.4

### ISSUE THREAD

**Issue by SiminXmas** [apiaryio/protagonist#184]
/usr/local/bin/api-mock -> /usr/local/lib/node_modules/api-mock/bin/api-mock

> protagonist@1.2.6 install /usr/local/lib/node_modules/api-mock/node_modules/protagonist
> node-gyp rebuild

  CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.o
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
make: *** [Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/api-mock/node_modules/protagonist
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
/usr/local/lib
└── (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protagonist@1.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protagonist@1.2.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protagonist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

**Comment by pksunkara** [comment]
Do you have updated Xcode developer tools? You need a C++ compiler which is installed by that.

**Comment by SiminXmas** [comment]
@pksunkara yes, I had updated Xcode (Version 8.3)

**Comment by kylef** [comment]
@SiminXmas Do you have the command line tools installed?

```shell
$ sudo xcode-select --install
```

**Comment by SiminXmas** [comment]
@kylef I had install command line tools when Xcode installed

**Comment by presto2116** [comment]
same problem here. have xcode installed and getting the same error

**Comment by kylef** [comment]
@presto2116 @SiminXmas Can you both run `xcode-select --install` and see what it says please. If they are installed it should tell you.

xcode-select may ask to agree to Xcode terms of license. Xcode is not required, just the command line tools.

```shell
$ sudo xcode-select --instal
```

**Comment by presto2116** [comment]
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
current xcode version is 8.3.1

**Comment by kylef** [comment]
Do you have homebrew installed? If so can you run `brew doctor` it's great at pinpointing some common problems.

```shell
$ brew doctor
```

**Comment by presto2116** [comment]
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  git
  mysql
  node
  python
  python34

**Comment by kylef** [comment]
> I should also point out that i am using node v0.12.7 due to project needs

Sorry we never got round to responding to you. Node 0.12 is no longer supported in Protagonist 2.0 and onwards, however you can use Protagonist 1.x to Node 0.12 support so pin to the older version.

Another solution would be to use the [`drafter-npm`](http://github.com/apiaryio/drafter-npm) package instead of Protagonist directly. Drafter NPM will attempt to build the C++ Protagonist module, but if it cannot then it falls back to drafter.js a pure JavaScript version which should be compatible with much older Node JS versions.
