### ISSUE TITLE
Node 10 Support

### ISSUE THREAD

**Issue by ejunker** [apiaryio/protagonist#199]
I am trying to use Node 10 but get this error.

```
In file included from ../src/annotation.cc:1:
In file included from ../src/protagonist.h:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
```

I think it is because it needs to use a newer version of nodejs/nan which supports node 10. It would also be nice to fix any deprecations.

**Comment by kylef** [comment]
We've fixed this in master (tests pass on Node 10 in #200) and I think v2.0.0-pre.0, we're just wrapping up Protagonist 2.0 (Drafter 4.0) so we can get a final 2.0 release out.

**Comment by pksunkara** [comment]
Releasing 2.0.0-pre.1 fixes this.
