### ISSUE TITLE
Build error for 1.6.8

### ISSUE THREAD

**Issue by j5ingh** [apiaryio/protagonist#226]
Hi,

I need [aglio](https://github.com/danielgtaylor/aglio) which is depending on protagonist@1.6.8 but I'm having issues with installing/building it with npm/node-gyp/manually.

> make: *** [Release/obj.target/protagonist/src/parse_async.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
> gyp ERR! System Darwin 18.2.0
> gyp ERR! command "/usr/local/Cellar/node/11.3.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/j5ingh/dev/my-project/node_modules/protagonist
> gyp ERR! node -v v11.3.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! protagonist@1.6.8 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the protagonist@1.6.8 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I've got the latest OS X version with python2.7 and a compiler through xCode.

Can someone help me out?

**Comment by kylef** [comment]
Hi @j5ingh,

Protagonist 1.x does not contain support for Node 11, you will either need to use Protagonist 2.x or downgrade to an older Node.

That said, Aglio optionally depends on the C++ parser Protagonist and you should still be able to use Aglio with our native JavaScript parser (it's a little less performance but probably not noticable for a lot of cases). I would imagine that the installation succeeded even if you saw that error and you should be able to continue using Aglio. Just note that it uses a much older version of the API Blueprint parser so newer changes may not be present.

Aglio is unfortunately unmaintained software and I don't think it will be updated to work with Protagonist 2.x.
