### ISSUE TITLE
segmentation fault error

### ISSUE THREAD

**Issue by eddiemoore** [apiaryio/protagonist#59]
Trying to turn this into a grunt plugin. However when I am trying to run the ```protagonist.parse``` method I occasionally get a segmentation fault
```
78598 segmentation fault
```

This seems to be coming from snowcrash

**Running:**
node v0.12.2
grunt: v0.4.5

**To reproduce:**
```shell
npm install --save-dev grunt-protagonist
```
**example.apib**
```markdown
# Group Users

## Users [/users]
### Create a new user [POST]

+ Attributes

    + email (string, required) - User's email address
    + username (string, required) - Username for user
    + password (string, required) - Password for user

+ Request (application/json)
    + Headers

            Authorization: Bearer ACCESS_TOKEN

    + Body

            {
              "email": "example@example.com",
              "username": "foobar",
              "password": "2xPaisdn",
            }
```

**Gruntfile.js**
```javascript
'use strict'

module.exports = function (grunt) {

  grunt.initConfig({
    protagonist: {
      src: 'example.apib'
    }
  });

  grunt.loadNpmTasks('grunt-protagonist');

  grunt.registerTask('default', ['protagonist']);
}
```

**Run:**
```shell
grunt
```

This should display an error. However it just passes the test and occasionally runs into errors when running the protagonist module

**Comment by eddiemoore** [comment]
https://github.com/eddiemoore/grunt-protagonist/issues/2

**Comment by pksunkara** [comment]
Hey @eddiemoore, the given blueprint is not giving any seg fault for me when trying to parse it with drafter.

**Comment by eddiemoore** [comment]
It only happens on occasion.
But it's not even returning the output from protagonist.
Try running my example setup a few times

**Comment by zdne** [comment]
Thanks for the report @eddiemoore!  What OS you are on? if posix, can you please run `gcc -v` if Windows what MSVC are you using?

**Comment by eddiemoore** [comment]
I am on:
```shell
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

**Comment by kylef** [comment]
At lot has changed in Protagonist since this issue was created. I'm unable to reproduce this problem with the latest versions of Drafter/Protagonist.

@eddiemoore Could you please verify if you are still having this problem with Protagonist 1.4.1.

**Comment by kylef** [comment]
I'm going to close this issue since we haven't heard back. If this is still an issue for anyone please let us know and we can re-open this issue.
