### ISSUE TITLE
Is Release build really optimized?

### ISSUE THREAD

**Issue by w-vi** [apiaryio/protagonist#61]
I've just looked at the gypi and gyp file and I can't find any cflags being set to `-O2`. Looking at the final gyp file in build I don't see any cflags at all so the compiler default is used which in case of clang and gcc is `-O0`. Have I missed something? If not wouldn't it be better to set release build to `-O2`?

**Comment by zdne** [comment]
@w-vi I haven't experiment with it. Instead, since it is build by node-gyp instead of regular gyp this is relying on node.js / node-gyp settings. But some verification of what is actually happening seems like a good idea!

**Comment by w-vi** [comment]
@zdne so I went to node-gyp and node.js sources to see how the whole thing is set up and node-gyp actually uses `-O3` as [common.gypi](https://github.com/joyent/node/blob/master/common.gypi) from node is always used when building with node-gyp. It sets the `Debug` flags to `-g -O0` too so no need for that either but what I'm now wondering about is whether the `common.gypi` from protagonist is not somehow interfering with the node.js one. Is it really necessary as it looks like it is a copy of node.js version maybe with some little tweaks.

**Comment by w-vi** [comment]
I've verified that it is optimized indeed ... thanks for patience I've learnt a lot about the node build system. So closing this question.

**Proof**: `V=1 make` in build directory

` g++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/wvi/.node-gyp/1.8.1/src -I/home/wvi/.node-gyp/1.8.1/deps/uv/include -I/home/wvi/.node-gyp/1.8.1/deps/v8/include -I../drafter/src -I../drafter/ext/snowcrash/src -I../drafter/ext/snowcrash/ext/markdown-parser/src -I../drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src -I../drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/html -I../drafter/ext/sos/src -I../node_modules/nan  -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -m64 -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/protagonist/src/v8_wrapper.o.d.raw  -c -o Release/obj.target/protagonist/src/v8_wrapper.o ../src/v8_wrapper.cc
`

**Comment by zdne** [comment]
Thanks @w-vi for investigation!
