### ISSUE TITLE
Installation of protagonist failed

### ISSUE THREAD

**Issue by tbremeyer** [apiaryio/protagonist#73]
I am trying to install protagonist (as a prerequisite for aglio). However the installation fails with the following output: 

```
npm install protagonist

> protagonist@0.20.0 install C:\Users\torsten.bremeyer\node_modules\protagonist
> node-gyp rebuild


C:\Users\torsten.bremeyer\node_modules\protagonist>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_module
s\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild) 
Warning: Missing input files:
C:\Users\torsten.bremeyer\node_modules\protagonist\build\drafter\ext\snowcrash\..\..\..\..\drafter\ext\snowcrash\src\Version.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v
100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio t
ools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\torsten.bremeyer\node_modules\protagonist\build\draft
er\libdrafter.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v
100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio t
ools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\torsten.bremeyer\node_modules\protagonist\build\draft
er\ext\snowcrash\libmarkdownparser.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v
100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio t
ools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\torsten.bremeyer\node_modules\protagonist\build\draft
er\ext\snowcrash\libsnowcrash.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v
100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio t
ools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\torsten.bremeyer\node_modules\protagonist\build\draft
er\libsos.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v
100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio t
ools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\torsten.bremeyer\node_modules\protagonist\build\draft
er\ext\snowcrash\libsundown.vcxproj]
npm : gyp ERR! build error 
At line:1 char:1
+ npm install protagonist
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (gyp ERR! build error :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
gyp
 
ERR!
 
stack
 Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp
 
ERR!
 
stack
     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp
 
ERR!
 
stack
     at ChildProcess.emit (events.js:110:17)
gyp
 
ERR!
 
stack
     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp
 ERR! System
 Windows_NT 6.1.7601
gyp
 
ERR!
 
command
 "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp
 
ERR!
 
cwd
 C:\Users\torsten.bremeyer\node_modules\protagonist
gyp
 ERR! 
node -v
 v0.12.4
gyp
 ERR! node-gyp -v
 v1.0.3
gyp
 
ERR!
 
not ok
 
npm
 
ERR!
 Windows_NT 6.1.7601
npm
 
ERR!
 
argv
 "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "protagonist"
npm
 
ERR!
 
node
 v0.12.4
npm
 ERR! 
npm 
 v2.10.1
npm
 
ERR! 
code
 ELIFECYCLE
npm
 ERR! protagonist@0.20.0 install: `node-gyp rebuild`
npm
 
ERR!
 Exit status 1
npm
 ERR! 
npm
 
ERR!
 Failed at the protagonist@0.20.0 install script 'node-gyp rebuild'.
npm
 
ERR!
 This is most likely a problem with the protagonist package,
npm 
ERR!
 not with npm itself.
npm
 ERR!
 Tell the author that this fails on your system:
npm
 
ERR!
     node-gyp rebuild
npm
 
ERR!
 You can get their info via:
npm 
ERR!
     npm owner ls protagonist
npm
 
ERR!
 There is likely additional logging output above.
npm
 
ERR!
 Please include the following file with any support request:
npm
 
ERR!
     C:\Users\torsten.bremeyer\npm-debug.log
```

Zdenek told me I need Visual Studio on my system. I do have Visual Studio 2013, but not VS 2010.

Can someone help me with this installation?

**Comment by zdne** [comment]
Have you tried to build this from MSVC command prompt?

**Comment by tbremeyer** [comment]
I just tried that, but I get the same error (only with a little different formatting).

**Comment by tbremeyer** [comment]
I tried to upgrade the snowcrash solution with Visual Studio 2013, but I get build errors:
Error	1	error C1083: Cannot open source file: '..\ext\markdown-parser\src\ByteBuffer.cc': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1xx	libmarkdownparser
Error	2	error C1083: Cannot open source file: '..\ext\markdown-parser\src\MarkdownNode.cc': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1xx	libmarkdownparser
Error	3	error C1083: Cannot open source file: '..\ext\markdown-parser\src\MarkdownParser.cc': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1xx	libmarkdownparser
Error	4	error C1083: Cannot open source file: '..\ext\markdown-parser\ext\sundown\src\autolink.c': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1	libsundown
Error	5	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	libsnowcrash
Error	6	error C1083: Cannot open source file: '..\ext\markdown-parser\ext\sundown\src\buffer.c': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1	libsundown
Error	7	error C1083: Cannot open source file: '..\ext\markdown-parser\ext\sundown\src\markdown.c': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1	libsundown
Error	8	error C1083: Cannot open source file: '..\ext\markdown-parser\ext\sundown\src\src_map.c': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1	libsundown
Error	9	error C1083: Cannot open source file: '..\ext\markdown-parser\ext\sundown\src\stack.c': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1	libsundown
Error	10	error C1083: Cannot open source file: '..\ext\markdown-parser\ext\sundown\html\houdini_href_e.c': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1	libsundown
Error	11	error C1083: Cannot open source file: '..\ext\markdown-parser\ext\sundown\html\houdini_html_e.c': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1	libsundown
Error	12	error C1083: Cannot open source file: '..\ext\markdown-parser\ext\sundown\html\html.c': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1	libsundown
Error	13	error C1083: Cannot open source file: '..\ext\markdown-parser\ext\sundown\html\html_smartypants.c': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\build\c1	libsundown
Error	14	error C1083: Cannot open include file: 'MarkdownParser.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\MSON.h	19	1	libsnowcrash
Error	15	error C1083: Cannot open include file: 'ByteBuffer.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\ModelTable.h	14	1	libsnowcrash
Error	16	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	libsnowcrash
Error	17	error C1083: Cannot open include file: 'ByteBuffer.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\ModelTable.h	14	1	libsnowcrash
Error	18	error C1083: Cannot open include file: 'ByteBuffer.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\ModelTable.h	14	1	libsnowcrash
Error	19	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	libsnowcrash
Error	20	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	libsnowcrash
Error	21	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Signature.h	12	1	libsnowcrash
Error	22	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	libsnowcrash
Error	23	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	libsnowcrash
Error	24	error C1083: Cannot open include file: 'ByteBuffer.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\ModelTable.h	14	1	libsnowcrash
Error	25	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	perf-libsnowcrash
Error	26	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	test-libsnowcrash
Error	27	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	28	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	29	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\test\test-Blueprint.cc	9	1	test-libsnowcrash
Error	30	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	31	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	32	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	33	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	34	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	test-libsnowcrash
Error	35	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	test-libsnowcrash
Error	36	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	37	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	38	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	39	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	40	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	41	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	42	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	43	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	44	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	45	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	46	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	47	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\test\test-RegexMatch.cc	9	1	test-libsnowcrash
Error	48	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	49	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	50	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	51	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	52	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	53	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	54	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	test-libsnowcrash
Error	55	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	C:\Users\torsten.bremeyer\Projects\Apiary\test\test-UriTemplateParser.cc	9	1	test-libsnowcrash
Error	56	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash
Error	57	error C1083: Cannot open include file: 'MarkdownNode.h': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\src\Blueprint.h	16	1	test-libsnowcrash
Error	58	error C1083: Cannot open include file: 'catch.hpp': No such file or directory	c:\users\torsten.bremeyer\projects\apiary\test\snowcrashtest.h	12	1	test-libsnowcrash

**Comment by XVincentX** [comment]
Hey @tbremeyer,
I just made a local test using **Windows 8.1**, **Visual Studio 2013**, **node 0.12.4**, **npm 2.10.1** and **Python 2.7**

Could you please share more information about your system configuration?
Thanks!

**Comment by Gingonic** [comment]
Could you explain me why protagonist needs to rebuild node-gyp? This realy blocks the usage of aglio for example, as every developer would have to install visual studio on it's local machine just to install that one module.

**Comment by XVincentX** [comment]
@Gingonic 
Protagonist does not need to rebuild node-gyp. It uses node-gyp to build the sources according to your machine architecture and set compiler.

But I agree with you that providing prebuilt binaries would help a lot of people to use protagonist without having to install several developer tools. I am thinking about [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp). What is your thought about, @z?

I think we can use appveyor to generate them, and then upload them somewhere.

**Comment by zdne** [comment]
@XVincentX unfortunately providing binary installation on Windows was and still is a huge issue do to (in)compatibility of runtime libraries amongst differ Windows versions.

**Comment by voor** [comment]
Hey guys, I know this is about Windows installation, but I wanted to point out we might be having a similar issue on more recent Linux kernels:

```
➜  ~  npm install -g protagonist
npm http GET https://registry.npmjs.org/protagonist
npm http 304 https://registry.npmjs.org/protagonist
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> protagonist@1.2.0-beta.1 install /home/voor/.npm/lib/node_modules/protagonist
> node-gyp rebuild

gyp: drafter/drafter.gyp not found (cwd: /home/voor/.npm/lib/node_modules/protagonist)
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.3-200.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/voor/.npm/lib/node_modules/protagonist
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

```

**Comment by pksunkara** [comment]
@voor That error log is about a different issue which occurred in our latest release. We will be fixing it soon and give a new release.

**Comment by pavelkornev** [comment]
@pksunkara any updates? I have same issue on OSX 10.11, npm 3.5.2, node 5.3.0

```
> protagonist@1.2.4 install /Users/Skay/Webserver/skaternames/api/node_modules/protagonist
> node-gyp rebuild

gyp: drafter/drafter.gyp not found (cwd: /Users/Skay/Webserver/skaternames/api/node_modules/protagonist) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Skay/Webserver/skaternames/api/node_modules/protagonist
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
```

**Comment by kylef** [comment]
@pavelkornev please try again now, released [protagonist 1.2.5](https://github.com/apiaryio/protagonist/releases/tag/v1.2.5) which should resolve your problem.

**Comment by pavelkornev** [comment]
@kylef that works! Thanks for a quick fix.

**Comment by zdne** [comment]
For what it is worth, if you are on Windows with MSVS2015 there is an issue with Node building tool and native extensions. As I've found out you need to set version of MSVS for GYP:

> Note: On Windows with MSVS 2015 make sure to run `$ set GYP_MSVS_VERSION=2015` prior to `$ apm install linter-api-blueprint`.
> (from https://github.com/zdne/linter-api-blueprint#installation)

This might apply to Aglio with Protagonist on Windows with MSVS2015...

**Comment by kylef** [comment]
I'm going to close this issue out since we haven't heard from the original creator in a while, and since the bug was originally created against Protagonist 0.20. I believe that many problems when installing Protagonist on Windows have been resolved in later versions of Protagonist and Drafter.

If anyone is still having any difficulty installing Protagonist please create a separate issue and we'd be happy to take a look.
