### ISSUE TITLE
Improve installation time for CI services

### ISSUE THREAD

**Issue by kylef** [apiaryio/protagonist#77]
Currently Protagonist (dredd) takes around a minute to install on CI services such as Travis CI and Circle CI which add considerable overhead to testing times where the tests take a few seconds to run.

Installing dredd increases the CI time by over a minute, which in my particular case ([Polls API](https://github.com/apiaryio/polls-api)) causes a **23 times** slowdown for the CI builds where my tests run in under 3 seconds. Dredd takes over a minute to install due to Protagonist compiling Drafter and Snowcrash.

![screen shot 2015-07-30 at 15 27 13](https://cloud.githubusercontent.com/assets/44164/8984097/9fc4181e-36cf-11e5-83d8-c8875d1e141d.png)

### Potential solutions

I'm sure we can improve this situation and I have a few potential solutions. Perhaps this isn't actionable in protagonist itself so this issue is mostly for discussion to find an outcome.

- We speak to Travis CI/Circle CI and try and get protagonist/dredd pre-installed
- We provide binary releases compatible with Travis CI and Circle CI
- We leverage and document how to use cache on Travis CI and Circle CI to prevent protagonist from being re-installed everytime

/cc @netmilk

**Comment by kylef** [comment]
Not to mention, this would speed up the build times for dredd and apiary too by over a minute.

**Comment by zdne** [comment]
> We provide binary releases compatible with Travis CI and Circle CI

I would like us to NOT provide binary installation. 

Another solution in a future would be to use a "remote API Blueprint" adapter in Fury.js that will be calling API Blueprint parsing API (and thus it won't need protagonist / binary)

**Comment by IvanGoncharov** [comment]
This issues cause severe problems in my use case, because I need to do `npm install` twice.
What about using standart Node.js approach, [node-pre-gyp](https://github.com/mapbox/node-pre-gyp)?

**Comment by pksunkara** [comment]
@IvanGoncharov Can you describe your use case a bit more? I don't understand why you need to do npm install twice.

**Comment by IvanGoncharov** [comment]
@pksunkara Travis use two separate environments to run test and deploy scripts.
In both cases I use the same scripts which depend on this lib.
So travis run `npm install` twice :(

**Comment by kylef** [comment]
I think [Drafter NPM](https://github.com/apiaryio/drafter-npm) sufficiently solves this problem. You can pass in the `--no-optional` flag to `npm install` to use the pure JavaScript version of Drafter. An update to tools such as Dredd is underway (https://github.com/apiaryio/dredd-transactions/pull/51).
