### ISSUE TITLE
Supporting MSON via Attributes 

### ISSUE THREAD

**Issue by yakovkhalinsky** [apiaryio/protagonist#83]
Are there any plans to add support for parsing MSON format via Attributes?

It's been noted that previously in Drafter.js that MSON is parsed by the same Blueprint API files are not parsed the same way via Protagonist.

Are there any plans to introduce this functionality back into Protagonist?

I notice that Dredd also still uses Drafter.js: https://github.com/apiaryio/dredd/blob/master/src/dredd.coffee#L153

**Comment by hendrikmaus** [comment]
I would also like to be enlightened on the plans regarding protagonist. As far as GitHub can tell, drafter.js deprecates in favour of protagonist. But the latter does not seem to offer a congruent feature set as @yakovkhalinsky points out. Cheers

**Comment by pksunkara** [comment]
@yakovkhalinsky Drafter.js tool uses Protagonist which uses C++ Drafter.

The purpose of C++ Drafter is to parse the API Blueprint. And Protagonist is the Node.js module wrapping C++ Drafter. Drafter.js is a Node.js module which expands the MSON AST in the API Blueprint AST and renders the sample body and schema.

So, if you want to see the sample body and schema, you have to use drafter.js and not protagonist.

PS: INFORMATION BELOW IS REALLY IMPORTANT

Currently, we are working on expanding the MSON Refract (AST is deprecated) and rendering the sample body and schema inside C++ Drafter itself (apiaryio/drafter#39 & apiaryio/protagonist#84) which when merged provides the sample body and schema in protagonist itself. I would recommend you to use those particular branches or wait until release to start using MSON because MSON AST is deprecated as mentioned in https://github.com/apiaryio/mson-ast

**Comment by pksunkara** [comment]
Please keep in mind that by we are also making [API Description Namespace](https://github.com/refractproject/refract-spec/blob/master/namespaces/api-description-namespace.md) the default output in the above mentioned release. You guys can still access the old API AST using an option.

**Comment by zdne** [comment]
Hey @yakovkhalinsky I've tried to explain the current situation here – https://github.com/Aconex/drakov/issues/60#issuecomment-134155329 – does this answer your question?

**Comment by yakovkhalinsky** [comment]
thanks guys, I appreciate the clarification :+1:

**Comment by catesandrew** [comment]
The mson refract is not correctly parsing right now as of v1.1.1. With `refract` I get this:

```json
{
  "element": "dataStructure",
  "content": [
    {
      "element": "Token Base",
      "meta": {
        "id": "Secret Token Base",
        "description": "    - client_id: nativeapp (required, string) - The identifier of the client.\n    - client_secret: hidden (required, string) - The secret password of the client.\n\n"
      }
    }
  ]
}
```

And with `ast` I get it parsed correctly as this:

```json
{
  "element": "dataStructure",
  "content": [
    {
      "element": "Token Base",
      "meta": {
        "id": "Secret Token Base"
      },
      "content": [
        {
          "element": "member",
          "meta": {
            "description": "The identifier of the client."
          },
          "attributes": {
            "typeAttributes": [
              "required"
            ]
          },
          "content": {
            "key": {
              "element": "string",
              "content": "client_id"
            },
            "value": {
              "element": "string",
              "content": "nativeapp"
            }
          }
        },
        {
          "element": "member",
          "meta": {
            "description": "The secret password of the client."
          },
          "attributes": {
            "typeAttributes": [
              "required"
            ]
          },
          "content": {
            "key": {
              "element": "string",
              "content": "client_secret"
            },
            "value": {
              "element": "string",
              "content": "hidden"
            }
          }
        }
      ]
    }
  ]
}
```

Moving to `refract` which looks awesome is broken so makes it extremely difficult to migrate to. The above are from a very simple example of data structures

```md
# Data Structures

## Token Base (object)
- Attributes
    - grant_type (enum[string], default, required)
        - client_credentials
        - password
        - authorization_code
        - refresh_token
    - state: 123 (string, optional) - Unique identifier to protect against CSRF.
    - scope: sqa (string, optional) - What is the scope of access being requested?

## Secret Token Base (Token Base)
    - client_id: nativeapp (required, string) - The identifier of the client.
    - client_secret: hidden (required, string) - The secret password of the client.
```

**Comment by pksunkara** [comment]
Actually, the old AST is also giving the same thing.

```json
          {
            "element": "dataStructure",
            "content": [
              {
                "element": "Token Base",
                "meta": {
                  "id": "Secret Token Base",
                  "description": "    - client_id: nativeapp (required, string) - The identifier of the client.\n    - client_secret: hidden (required, string) - The secret password of the client.\n"
                }
              }
            ]
          }
```

You have extra starting spaces on the last 2 lines of your document which is causing this.

**Comment by pksunkara** [comment]
I am also closing this issue since it's been resolved.
