### ISSUE TITLE
Validation results?

### ISSUE THREAD

**Issue by khaliddermoumi** [apiaryio/protagonist#92]
Hi,

since protagonist is replacing drafter, I have expected to get some validation information from protagonist (like the "warnings"-array of drafter).
But no matter how broken the input is I am feeding protagonist with, it never complains and there is no indication of any error.
How do I get validation information?
(I am using 1.0.0)

Regards and thanks for your work,
k

**Comment by pksunkara** [comment]
@khaliddermoumi We are currently working on adding it to protagonist.

**Comment by khaliddermoumi** [comment]
Thanks for your answer! Any idea when approx. the feature will be released?

**Comment by iam-merlin** [comment]
@khaliddermoumi I think this should be open while this feature is not release for tracking.

**Comment by pksunkara** [comment]
This has been fixed in master now.

**Comment by iam-merlin** [comment]
@pksunkara good to know :D, thx
